# Generated by Django 3.0.5 on 2020-04-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200408_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='userid',
            new_name='author',
        ),
    ]
